version: '3.8'

services:
  app:
    #command: go test ./... -v -race
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./storage:/app/storage
      - ./config:/app/config
    environment:
      CONFIG_PATH: /app/config/local.yaml
    depends_on:
        - db

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./migrate"]
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations
    environment:
      GOPROXY: "https://goproxy.io"
      CONFIG_PATH: /app/config/local.yaml
    depends_on:
      - db

  db:
    container_name: cloud-go-testtask-db-1
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: