env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
db_config:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  db_name: "playlist"
  ssl_mode: "disable"